#!/usr/bin/env sh
set -e
# Server postinstall script to install daemon
chmod 755 /usr/local/Repetier-Server/bin/installLaunchd.sh
chmod 755 /usr/local/Repetier-Server/bin/uninstallLaunchd.sh
cp /usr/local/Repetier-Server/etc/RepetierServer.plist /Library/LaunchDaemons
chown root /Library/LaunchDaemons/RepetierServer.plist
launchctl unload /Library/LaunchDaemons/RepetierServer.plist
chmod 644 /Library/LaunchDaemons/RepetierServer.plist
launchctl load /Library/LaunchDaemons/RepetierServer.plist
# Open Server
# open http://localhost:3344
exit 0
