<div class="container">
    <div class="row">
        <div class="col-12">
            <h1><?php _("PROJECT_NAME_VERSION") ?> Licence</h1>

            <p>&copy; 2013 Hot-World GmbH & Co. KG<br>
                Part developed by Hot-World GmbH & Co. KG are distributed under the Apache V2 licence.
                The sources contain software from 3rd parties with different licences.</p>

            <p>Licensed under the Apache License, Version 2.0 (the "License"); you may not use this work
                except in compliance with the License. You may obtain a copy of the License in the
                LICENSE file, or at:</p>

            <a href="http://www.apache.org/licenses/LICENSE-2.0" target="_blank">http://www.apache.org/licenses/LICENSE-2.0</a>

            <p>Unless required by applicable law or agreed to in writing, software distributed under the
                License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
                either express or implied. See the License for the specific language governing
                permissions and limitations under the License.</p>
            <hr>

            <h2>3rd party software used in <?php _("PROJECT_NAME") ?></h2>

            <h3>moFileReader - A simple .mo-File-Reader</h3>

            <p>Copyright (C) 2009 Domenico Gentner (scorcher24@gmail.com)
                All rights reserved. </p>

            <p>Redistribution and use in source and binary forms, with or without
                modification, are permitted provided that the following conditions
                are met:</p>
            <ol>
                <li> Redistributions of source code must retain the above copyright
                    notice, this list of conditions and the following disclaimer.
                </li>
                <li> Redistributions in binary form must reproduce the above copyright
                    notice, this list of conditions and the following disclaimer in the
                    documentation and/or other materials provided with the distribution.
                </li>

                <li> The names of its contributors may not be used to endorse or promote
                    products derived from this software without specific prior written
                    permission.
                </li>
            </ol>
            <p> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
                "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
                LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
                A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
                CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
                EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
                PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
                PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
                LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
                NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
                SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
            </p>

            <h3>JSON Spirit</h3>

            Homepage: <a
                href="http://www.codeproject.com/Articles/20027/JSON-Spirit-A-C-JSON-Parser-Generator-Implemented"
                target="_blank">http://www.codeproject.com/Articles/20027/JSON-Spirit-A-C-JSON-Parser-Generator-Implemented</a>

            <p>Copyright John W. Wilkinson 2007 - 2013</p>

            <p>Distributed under the MIT License, see accompanying file LICENSE.txt</p>

            <h3>POCO</h3>
            Homepage: <a href="http://pocoproject.org/" target="_blank">http://pocoproject.org/</a>

            <p>Boost Software License - Version 1.0 - August 17th, 2003
            </p>

            <p>

                Permission is hereby granted, free of charge, to any person or organization
                obtaining a copy of the software and accompanying documentation covered by
                this license (the "Software") to use, reproduce, display, distribute,
                execute, and transmit the Software, and to prepare derivative works of the
                Software, and to permit third-parties to whom the Software is furnished to
                do so, all subject to the following:
            </p>

            <p>

                The copyright notices in the Software and this entire statement, including
                the above license grant, this restriction and the following disclaimer,
                must be included in all copies of the Software, in whole or in part, and
                all derivative works of the Software, unless such copies or derivative
                works are solely in the form of machine-executable object code generated by
                a source language processor.
            </p>

            <p>
                THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
                IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
                FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
                SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
                FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
                ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
                DEALINGS IN THE SOFTWARE.</p>

            <h3>Boost</h3>
            Homepage: <a href="http://www.boost.org/" target="_blank">http://www.boost.org/</a>

            <p>Boost Software License - Version 1.0 - August 17th, 2003
            </p>

            <p>

                Permission is hereby granted, free of charge, to any person or organization
                obtaining a copy of the software and accompanying documentation covered by
                this license (the "Software") to use, reproduce, display, distribute,
                execute, and transmit the Software, and to prepare derivative works of the
                Software, and to permit third-parties to whom the Software is furnished to
                do so, all subject to the following:
            </p>

            <p>

                The copyright notices in the Software and this entire statement, including
                the above license grant, this restriction and the following disclaimer,
                must be included in all copies of the Software, in whole or in part, and
                all derivative works of the Software, unless such copies or derivative
                works are solely in the form of machine-executable object code generated by
                a source language processor.
            </p>

            <p>
                THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
                IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
                FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
                SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
                FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
                ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
                DEALINGS IN THE SOFTWARE.</p>

            <h3>Twitter Bootstrap</h3>

            <p>Homepage: <a href="https://github.com/twitter/bootstrap" target="_blank">https://github.com/twitter/bootstrap</a>
            </p>

            <p>Copyright 2012 Twitter, Inc.</p>

            <p>Licensed under the Apache License, Version 2.0 (the "License"); you may not use this work
                except in compliance with the License. You may obtain a copy of the License in the
                LICENSE file, or at:</p>

            <a href="http://www.apache.org/licenses/LICENSE-2.0" target="_blank">http://www.apache.org/licenses/LICENSE-2.0</a>

            <p>Unless required by applicable law or agreed to in writing, software distributed under the
                License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
                either express or implied. See the License for the specific language governing
                permissions and limitations under the License.</p>

            <h3>Font Awesome</h3>

            <p>Homepage: <a href="http://jquery.com/" target="_blank">http://fortawesome.github.com/Font-Awesome/</a>
            </p>

            <p>Licence: SIL Open Font License</p>
            <ul>
                <li>The Font Awesome font is licensed under the SIL Open Font License - http://scripts.sil.org/OFL.</li>
                <li>Font Awesome CSS, LESS, and SASS files are licensed under the MIT License -
                    http://opensource.org/licenses/mit-license.html.
                </li>
                <li>The Font Awesome pictograms are licensed under the CC BY 3.0 License -
                    http://creativecommons.org/licenses/by/3.0/
                </li>
                <li>Attribution is no longer required in Font Awesome 3.0, but much appreciated: Font Awesome by Dave
                    Gandy -
                    http://fortawesome.github.com/Font-Awesome.
                </li>
            </ul>

            <h3>jQuery</h3>

            <p>Homepage: <a href="http://jquery.com/" target="_blank">http://jquery.com/</a></p>

            <p>Licence: MIT Licence</p>

            <h3>jQuery form</h3>

            Homepage: <a href="http://malsup.com/jquery/form/" target="_blank">http://malsup.com/jquery/form/</a>

            <p>The jQuery Form plugin is dual licensed under the MIT and GPL licenses:</p>
            <ul>
                <li><a href="http://malsup.github.com/mit-license.txt">MIT</a></li>
                <li><a href="http://malsup.github.com/gpl-license-v2.txt">GPL</a></li>
            </ul>
            <p>You may use either license. The MIT License is recommended for most projects because
                it is simple and easy to understand and it places almost no restrictions on what you can
                do with the plugin.</p>

            <p>If the GPL suits your project better you are also free to use the plugin under that license.</p>

            <p>You don't have to do anything special to choose one license or the other and you don't
                have to notify anyone which license you are using. You are free to use the jQuery Form
                Plugin in commercial projects as long as the copyright header is left intact.</p>

        </div>
    </div>
</div>